.\" $Id: wftopfa.1,v 1.1 2004/01/14 16:59:47 atai Exp $
.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de>
.TH WFTOPFA 1 "8.Juli 2002" 7.06 Ghostscript \" -*- nroff -*-
.SH NAME
wftopfa \- konvertiert eine Wadalab basierte Schrift ins Postscript .PFA- (oder .PFB-)Format mittels Ghostscript.
.SH SYNTAX
\fBwftopfa\fR \fISchriftname\fR
.SH BESCHREIBUNG
Das Skript ruft
.BR gs (1)
auf, um eine Wadalab basierte Schrift in das Postscript .PFA- (oder .PFB-)Format zu konvertiern.
.SH SIEHE AUCH
gs(1)
.SH VERSION
Das Dokument wurde zuletzt für Ghostscript Version 6.0 durchgesehen.
.SH AUTOR
artofcode LLC ist der Hauptautor von Ghostscript.
Russell J. Lang <rjl@aladdin.com> ist der Autor des Hauptteils des MS-Windows Quelltexts in Ghostscript.
Diese Manpage ist von George Ferguson.
