.\" $Id: wftopfa.1,v 1.4 2005/05/09 22:04:37 Arabidopsis Exp $
.TH WFTOPFA 1 "9 May 2005" 8.16 Ghostscript \" -*- nroff -*-
.SH NAME
wftopfa \- Convert a Wadalab base font to Postscript .PFA (or .PFB)
format using ghostscript
.SH SYNOPSIS
\fBwftopfa\fR \fIfontname\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a Wadalab base font to Postscript .PFA (or .PFB)
format.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 8.16.
.SH AUTHOR
artofcode LLC and Artifex Software, bug-gs at ghostscript.com, are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
