#!/bin/sh
# $Id: bdftops,v 1.4 2007/05/07 11:22:07 Arabidopsis Exp $

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gs

exec $GS_EXECUTABLE -q -dBATCH -dNODISPLAY -- bdftops.ps "$@"
