#!/bin/sh
# $Id: bdftops,v 1.6 2010/07/10 22:02:36 Arabidopsis Exp $

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gs
gs="`dirname $0`/$GS_EXECUTABLE"
if test ! -x "$gs"; then
	gs="$GS_EXECUTABLE"
fi
GS_EXECUTABLE="$gs"

exec "$GS_EXECUTABLE" -q -P- -dSAFER -dBATCH -dNODISPLAY -- bdftops.ps "$@"
