#!/bin/sh
# $Id: gslj,v 1.3 2006/03/02 22:26:14 Arabidopsis Exp $

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gs

exec $GS_EXECUTABLE -q -sDEVICE=laserjet -r300 -dNOPAUSE -sPROGNAME=$0 -- gslp.ps --heading-center "`date`" "$@"
