#!/bin/sh
# $Id: pphs,v 1.2 2004/02/14 22:20:04 atai Exp $
# Print the Primary Hint Stream from a linearized PDF file.  Usage:
#	pphs filename.pdf
# Output goes to stdout.

exec gs -q -dNODISPLAY -- pphs.ps "$@"
