#!/bin/sh
# $Id: printafm,v 1.3 2007/05/07 11:22:07 Arabidopsis Exp $
# Print the metrics from a font in AFM format.  Usage:
#	printafm fontname
# Output goes to stdout.

exec gs -q -dNODISPLAY -- printafm.ps "$@"
