#!/bin/sh
# $Id: printafm,v 1.2 2004/02/14 22:20:04 atai Exp $
# Print the metrics from a font in AFM format.  Usage:
#	printafm fontname
# Output goes to stdout.

exec gs -q -dNODISPLAY -- printafm.ps "$@"
