#!/bin/sh
# $Id: printafm,v 1.1 2004/01/14 16:59:47 atai Exp $
# Print the metrics from a font in AFM format.  Usage:
#	printafm fontname
# Output goes to stdout.

exec gs -q -dNODISPLAY -- printafm.ps "$@"
