#!/bin/sh
# $Id: ps2pdf,v 1.2 2004/02/14 22:20:04 atai Exp $
# Convert PostScript to PDF.

# Currently, we produce PDF 1.2 by default, but this is not guaranteed
# not to change in the future.
exec ps2pdf12 "$@"
