#!/bin/sh
# $Id: ps2pdf13,v 1.5 2010/07/10 22:02:35 Arabidopsis Exp $
# Convert PostScript to PDF 1.3 (Acrobat 4-and-later compatible).
ps2pdfwr="`dirname $0`/ps2pdfwr"
if test ! -x "$ps2pdfwr"; then
	ps2pdfwr="ps2pdfwr"
fi
exec "$ps2pdfwr" -dCompatibilityLevel=1.3 "$@"
