#!/bin/sh
# $Id: ps2pdf,v 1.4 2007/05/07 11:22:07 Arabidopsis Exp $
# Convert PostScript to PDF.

# Currently, we produce PDF 1.4 by default, but this is not guaranteed
# not to change in the future.
exec ps2pdf14 "$@"
