#!/bin/sh
# $Id: ps2pdf,v 1.3 2006/06/16 12:55:14 Arabidopsis Exp $
# Convert PostScript to PDF.

# Currently, we produce PDF 1.4 by default, but this is not guaranteed
# not to change in the future.
exec ps2pdf14 "$@"
