#!/usr/bin/env python2.2
# -*- Mode: python -*-

#    Copyright (C) 2001 Artifex Software Inc.
# 
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2
#  as published by the Free Software Foundation.
#
#
#  This software is provided AS-IS with no warranty, either express or
#  implied. That is, this program is distributed in the hope that it will 
#  be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  59 Temple Place, Suite 330, Boston, MA, 02111-1307.
# 
# For more information about licensing, please refer to
# http://www.ghostscript.com/licensing/. For information on
# commercial licensing, go to http://www.artifex.com/licensing/ or
# contact Artifex Software, Inc., 101 Lucas Valley Road #110,
# San Rafael, CA  94903, U.S.A., +1(415)492-9861.

# $Id: dump_testdb,v 1.1 2004/02/14 23:13:10 atai Exp $

#
# dump_testdb [<dbfile>]
#
# dumps (prints out) the contents of the testdatadb

import sys, anydbm, gsconf

if len(sys.argv) == 2:
    print "opening ", sys.argv[1]
    db = anydbm.open(sys.argv[1])
else:
    db = anydbm.open(gsconf.testdatadb)

for k in db.keys():
    print db[k], k

