#!/usr/bin/env python
# -*- Mode: python -*-

#    Copyright (C) 2001 Artifex Software Inc.
# 
# This file is part of GNU ghostscript
#
# GNU ghostscript is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2, or (at your option) any later version.
#
# This software is provided AS-IS with no warranty, either express or
# implied. That is, this program is distributed in the hope that it will 
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA, 02110-1301.
# 
# For more information about licensing, please refer to
# http://www.ghostscript.com/licensing/. For information on
# commercial licensing, go to http://www.artifex.com/licensing/ or
# contact Artifex Software, Inc., 101 Lucas Valley Road #110,
# San Rafael, CA  94903, U.S.A., +1(415)492-9861.

# $Id: run_regression,v 1.3 2005/05/02 00:03:35 Arabidopsis Exp $

#
# run_regression
#
# runs ghostscript regression tests

import sys
import anydbm
import gstestutils, gsconf
import check_all
import gscheck_all

track = 0
if len(sys.argv) > 1:
    if sys.argv[1] == "--track":
        track = 1

        db = anydbm.open(gsconf.get_dailydb_name(), "n")
        db.close()
        
suite = gstestutils.GSTestSuite()

# Add tests based on running Ghostscript.
gscheck_all.addTests(suite, gsroot=gsconf.gsroot, track=track)

# Add tests not based on actually running Ghostscript.
check_all.addTests(suite, gsroot=gsconf.gsroot)

# run all the tests
runner = gstestutils.GSTestRunner(verbosity=2)
result = runner.run(suite)

